site_name: SCU-CTF 练习平台 WriteUp

repo_url: https://github.com/scu-ctf/scu-ctf.github.io

theme:
  name: "material"
  language: "zh"
  palette:
    primary: "white"
    accent: "red"
  logo:
    icon: "school"
  feature:
    tabs: true
  font:
    text: "Noto Sans"
    code: "Source Code Pro"

# Customization
extra:
  search:
    language: "jp"
  disqus: "ctf-wiki"
  copyright: "CC BY-NC-SA 4.0"

extra_javascript:
  - "https://cdnjs.loli.net/ajax/libs/pangu/3.3.0/pangu.min.js"
  - "_static/js/extra.js"
  - "https://cdnjs.loli.net/ajax/libs/mathjax/2.7.2/MathJax.js?config=TeX-MML-AM_CHTML"

extra_css:
  - "_static/css/extra.css"

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
